### ISSUE TITLE
Model license not specified

### ISSUE THREAD

**Issue by ville-k** [yahoo/open_nsfw#54]
According to the README, the code for evaluating the open_nsfw model is licensed under BSD 2 license. The README does not specify the license of the trained model.  Is it considered code and also covered by BSD 2 license?

**Comment by gyehuda** [comment]
I'm not a lawyer, and would welcome correction on the legal details here. But I am the person who licensed this code for your use under the BSD license. The code is code -- and thus an open source license applies. As for the model, I'm not sure if the "Structure Sequence, and Organization" aspect of copyright law applies -- thus treating the model to be subject to the same copyright protection and thus being licensed under the BSD, or if it's "content" and we should use a CC-BY license. Either way, please consider this permissively licensed. We intent to grant you broad rights to use, modify, copy, distribute, and perform the code _and_ the model. We ask that BSD-style terms apply (to give Yahoo credit for the work since that makes open source fair and kind).
